export default [
  {
    name: 'UNIVERSITY SENTIMENT ANALYSIS --- uchicagosecrets',
    description: 'As part of the UChicago Hackathon in an in-person team environment, we tackled the issue of mental health on college campuses by utilizing natural language processing to provide sentiment analysis on anonymous university Facebook pages. This program was written entirely on Python and involved the application of machine learning, web-scraping, and Matplotlib, a graph visualization tool. Click on the circle to see the code for this project.',
    textcolor: '#052c65',
    css: 'linear-gradient(to top, #052c65 0%, #94dee7 100%)',
    height: 210,
    link: 'https://github.com/philipchenaux/uchicagosecrets',
  },
  {
    name: 'CACHE SIMULATOR AND UNIX SHELL --- computersystems',
    description: 'After recently completing a course on machine code and instruction set architecture (ISA), I used my understanding of computer and operating systems to implement a cache simulator that reproduces a computer’s efficient data storage system. The project necessitated an understanding of how computers encode where to read and write data based on the address. I also learned about the relative merits of different cache structures and an LRU scheme. Additionally, I also programmed my custom Unix shell, which executes like Bash with added functionalities. This project used a range of system and library calls in C, as well as a particular focus on accounting for all command-line input variants, which required comprehensive white-box testing of all edge-cases. Click on the circle to see the code for this project.',
    textcolor: '#0E0C0B',
    css: 'linear-gradient(135deg, #0E0C0B 0%, #373D4A 100%)',
    height: 190,
    link: 'https://github.com/philipchenaux/computersystems',
  },
  {
    name: 'TEXT BASED GAME ENGINE --- chiventure',
    description: 'A recent project within a team setting that operated remotely, was to design and implement features within a text-based game engine. This large-scale project taught me how to effectively use Git by utilizing branches, dealing with merge conflicts, or using a range of tools to address bugs in the code like git bisect. Moreover, I familiarized myself with open-source build tools like CMake and Travis CI. Click on the circle to see the code for this project.',
    textcolor: '#151515',
    css: 'linear-gradient(to top, #FCF6F5FF 0%, #2BAE66FF  100%)',
    height: 210,
    link: 'https://github.com/philipchenaux/chiventure',
  },
  {
    name: 'MEMORY ALLOCATION IN C --- memory_alloc',
    description: 'This program essentially user to request a certain number of bytes, which will then be malloced accordingly. The program includes capabilities that allow for memory to be compacted or split based on the number of bytes required. The available memory was stored in a binary search tree for efficiency. Click on the circle to see the code for this project.',
    textcolor: '#2F0502',
    css: 'linear-gradient(120deg, #2D2926FF 0%, #E94B3CFF 100%)',
    height: 180,
    link: 'https://github.com/philipchenaux/computersystems',
  },
  {
    name: 'PORTFOLIO --- mywebsite',
    description: 'This website was coded using the React.js framework utilizing Javascript, HTML, and CSS. The landing page use react-spring to crete the animation and parallax effect. Additional libraries used are react-router, react-measure, react-scroll and react-bootsrap',
    textcolor: '#8348FF',
    css: 'linear-gradient(to top, #8348FF 0%, #00FFA3 100%)',
    height: 200,
    link: '',
  },
  {
    name: 'DATA CENTER RESEARCH ANALYST ----- east asia innovation challenge',
    description: 'Conducted primary research and aggregated secondary sources on the data center industry in East Asia. Developed a technical understanding of how the different data centers work and operate, in addition to identifiying potential areas for growth. Recommended a series of case questions to be used as the focus for the student consulting team working on the East Asia Innovation Challenge. Click on the circle to view the research I collated for this project.',
    textcolor: '#00203FFF',
    css: 'linear-gradient(120deg, #00203FFF 0%, #ADEFD1FF 100%)',
    height: 200,
    link: 'https://uchicago.box.com/s/3mxmchl5g7pz8r2onha1re6azlovozwc',
  },
  {
    name: 'ASTROPHYSICS RESEARCH PROJECT --- hong kong university labratory for space research',
    description: 'Astrophysics research project at the Labratory for Space Research. Used HASH database to compile morphology, angular diameter, and spectral line data of very low excitation planetary (vle) nebulae. Logged data into the IRAF analysis program to make subsequent spectral analysis. Looked for unusual correlations between temperatures, densities, and other characteristics.',
    textcolor: '#89ABE3FF',
    css: 'linear-gradient(to top, #FCF6F5FF 0%, #89ABE3FF 100%)',
    height: 200,
    link: '',
  },
  {
    name: 'SOLO BIKEPACKING TRIP --- hokkaido2020',
    description: 'Cycled 2500km in 3 weeks to circumnavigate the Northern island of Japan, Hokkaido, alone. Involved sleeping in a tent, and riding between 100 to 200km per day between small Japanese towns. Documented the distressing state of many Japanese towns suffering from an ageing population that has been exacerbated by Covid-19. A website covering my trip is in progess. Click on the circle to view my route on Strava.',
    textcolor: '#DD4132FF',
    css: 'linear-gradient(to top, #DD4132FF 0%, #9E1030FF 100%)',
    height: 200,
    link: 'https://www.strava.com/athletes/18799309#interval_type?chart_type=miles&interval_type=month&interval=202008&year_offset=0',
  },
  {
    name: 'STRATEGY CONSULTANT - phoenix development fund',
    description: 'Provide strategy consulting for non-profits and small businesses across the South Side of Chicago. Current Project: Focus on the growth & development work-stream of a small vegan restaurant through creating tactical manuals and training strategies for the business. Click on the circle to view our team\'s website',
    textcolor: '#FFBE7BFF',
    css: 'linear-gradient(to top, #FFBE7BFF 0%, #FFA351FF 100%)',
    height: 200,
    link: 'https://www.strava.com/athletes/18799309#interval_type?chart_type=miles&interval_type=month&interval=202008&year_offset=0',
  },
  {
    name: 'PROFESSIONAL TRIATHLETE - hong kong national team',
    description: 'Member of Hong Kong National Triathlon Team which involved racing across Asia and Europe with 18-30 training hours per week, divided between swimming, biking, and running. Spent 2 months during 2019 summer at an elite high-altitude training base in St. Moritz, Switzerland with world-class professionals. Click on the circle to view my triathlon profile.',
    textcolor: '#00239CFF',
    css: 'linear-gradient(120deg, #00239CFF 0%, #E10600FF 100%)',
    height: 190,
    link: 'https://www.triathlon.org/athletes/profile/121578/philip_sato',
  },
  {
    name: 'PEER MENTOR - university of chicago mentorship progam',
    description: 'Working with the college\'s Orientation Programming and Orientation to ease the transition for incoming freshman into the University of Chicago through meeting and online communications.',
    textcolor: '#990011FF',
    css: 'linear-gradient(120deg, #990011FF 0%, #FCF6F5FF 100%)',
    height: 170,
    link: '',
  },
  {
    name: 'STUDENT TUTOR - mast tutoring',
    description: 'Student tutor on subjects spanning from Mathematics, Physics, and Computer Science across the IB, IGCSE, and SAT syllabi.',
    textcolor: '#195190FF',
    css: 'linear-gradient(to top, #195190FF 0%, #A2A2A1FF 100%)',
    height: 200,
    link: '',
  },
  {
    name: 'HEAD PREFECT - german swiss international school',
    description: 'One of two head prefects selected by teachers, works closely with school administration and teachers. Coordinate, organize, and administer school-related events, such as tours and graduation. Responsible for management of 17 prefects, and indirect management of additional junior prefects.',
    textcolor: '#2C5F2D',
    css: 'linear-gradient(120deg, #2C5F2D 0%, #97BC62FF 100%)',
    height: 200,
    link: '',
  },
  {
    name: 'CO-FOUNDER - primary sports mentorship program',
    description: 'Involves coaching/teaching sports lessons to primary school students to motivate interest. Synthesized lesson plans and organized external sporting events; teaching experience with young students.',
    textcolor: '#A2A2A1FF',
    css: 'linear-gradient(to top, #F1F4FFFF 0%, #A2A2A1FF 100%)',
    height: 200,
    link: '',
  }
]